### ISSUE TITLE
cannot xtfrm data frames

### ISSUE THREAD

**Issue by zhan0521** [AparicioJohan/MrBeanApp#12]
I have tried running a SpATS analysis in Mr. Bean on two versions of R: 4.1.3 and 4.2.0. Both give this warning ("Warning: cannot xtfrm data frames"), but the newer version does not allow analysis to continue, while the older version does. This issue is still persisting in 4.2.0 version.

**Comment by AparicioJohan** [comment]
Hi,

I'm running a SpATS analysis under the same environment that you mentioned, and I don't see any warning message or error.
Could you please clarify in which part you see the error?

Best wishes!

**Comment by zhan0521** [comment]
Hi Johan,

Thanks for replying! The error shows when I click the Run Model button. MR
Bean works well with the other options - ASReml, two-Stage Analysis or
Analysis with lme4.

 I just installed MrBean on a different computer, and MrBean worked fine.
This is really strange.

Julia

**Comment by AparicioJohan** [comment]
Hi Julia,

Perhaps you had a previous version of the package, because it was solved in #9.
Glad to hear that it is running now!

Best,
Johan
