### ISSUE TITLE
Allow running MET analysis with default weights

### ISSUE THREAD

**Issue by jajberni** [AparicioJohan/MrBeanApp#3]
At the moment, it is necessary to select the column of the weights when doing a MET analysis. 

It would be nice to be able to leave it empty and use a default (e.g. 1.0) value if nothing is selected. At least for performing a quick analysis using the outputs from previous exported predictions.

**Comment by AparicioJohan** [comment]
That's an excellent point!
I updated the default option as 1 if weights is empty.
Thank you.

`https://github.com/AparicioJohan/MrBeanApp/commit/5f0cdee2cd72ad2bb418d38a421c07f5fc98a104`
