### ISSUE TITLE
pedigree  and kinship mtrices for partail replicated design

### ISSUE THREAD

**Issue by Mghanbari43** [AparicioJohan/MrBeanApp#8]
Hi and thanks for the lovely package,
I am just wondering if you have any plans to add the NRM or genomic kinship matrix to the single and multi-sites models. 
I think it would be very useful for model convergence in partially replicated designs in practice.

Thanks,
Mohammad

**Comment by AparicioJohan** [comment]
Hi dear Mohammad,

Thanks for your feedback. 
Have you tried to use the module GBLUP?

**Comment by Mghanbari43** [comment]
Hey Johan,
Thanks for the reply! Yes, I looked at the GBLUP added option and it looks interesting. But my question is more about using molecular markers or pedigree data to fit mixed models in single-site models (ASReml-R bases) and MET.
It is already great software but there is always room for improvement, especially for practical breeding data in which trials are partially replicated and information from relatives helps better estimation of BLUPs for genotypes.

**Comment by AparicioJohan** [comment]
Hey Mohammad,

The idea of the GBLUP module is to use it as a two-stage approach. In the first stage, we get the BLUEs, and in the second stage, we add the molecular markers.
What you are recommending is to implement a full one-stage approach where we add everything at once for both single trials and multi-environmental trials. It can be possible, but there would be some difficulties.
For sure there is always room for improvements :)

**Comment by Mghanbari43** [comment]
Thanks, it is more clear to me.
